apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prod/
- stage/

commonLabels:
  Department: engineering

namespace: frontend

namePrefix: kustomize-

commonAnnotations:
  logging: verbose
